### PR TITLE
Don't reencode MP3 when pitch is 1

### LINKED ISSUE #22: Don't reencode MP3 when pitch isn't changed
**Is your feature request related to a problem? Please describe.**
Currently, when downloading a voice clip as MP3 on newer Windows versions the program reencodes the downloaded MP3 even if the pitch is set to 1, resulting in quality degradation/generation loss.

**Describe the solution you'd like**
The program should just save the MP3 as-is if the pitch is not being changed.

**Describe alternatives you've considered**
Running the program in compatibility mode for Windows 7 to revert to legacy behavior doesn't work, as it doesn't change the reported Windows version (the way it's being checked here).

### PR DESCRIPTION
**Pull request by osyu**
Resolves #22.

### CODE REVIEW

**Review by osyu — COMMENTED** [review]
Comparing floats like this is pretty ugly but I had to please Codacy

**Comment by weespin** [comment]
Thanks I'll approve merge it

**Comment by weespin** [comment]
Thanks I'll merge it

**Comment by weespin** [comment]
Thanks! ❤️

**Pull request merged**
